/** Declaration file generated by dts-gen */
declare module "webgl-debug" {

  export function glEnumToString(value: any): any;

  export function glFunctionArgToString(functionName: any, numArgs: any, argumentIndex: any, value: any): any;

  export function glFunctionArgsToString(functionName: any, args: any): any;

  export function init(ctx: any): void;

  export function makeDebugContext(ctx: any, opt_onErrorFunc: any, opt_onFunc: any, opt_err_ctx: any, ...args: any[]): any;

  export function makeLostContextSimulatingCanvas(canvas: any, ...args: any[]): any;

  export function mightBeEnum(value: any): any;

  export function resetToInitialState(ctx: any): void;

}